import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Score",
  description: "Generated by Kelompok Proteus",
  authors: [
    {
      name: "Rafly",
      url: "https://github.com/Raflysaputra23/proteus-scorekata",
  }],
  keywords: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Score", "Proteus"],
  openGraph: {
    title: "Score",
    description: "Generated by Kelompok Proteus",
    url: "https://github.com/Raflysaputra23/proteus-scorekata",
    siteName: "Score",
    locale: "en-US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    card: "summary_large_image",
    title: "Score",
    description: "Generated by Kelompok Proteus",
    creator: "@Raflysaputra23",
  },
  

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
